[package]
name = "vexedaa/metaplugin"
description = "A springboard for easier plugin development"
license = "gpl-3.0"
version = "0.5.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@1.2.0"